### PR TITLE
Adding changelog and updating readme file with same

### PR DESCRIPTION
**Pull request by justjais**
##### SUMMARY

Adding changelog and updating readme file with same

##### ISSUE TYPE

- Doc Pull Request

##### COMPONENT NAME

ibm.qradar

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by justjais** [comment]
@maxamillion @samccann Please review and approve the PR

**Comment by justjais** [comment]
@maxamillio/@pabelanger can you apply gate label to the PR, as it seems I don’t have the required privileges to apply the respective label xD.

**Comment by maxamillion** [comment]
This is spectacular, thank you @justjais !!!

**Comment by justjais** [comment]
np @maxamillion and thank u for letting the PR through the gate xD

**Pull request merged**
